OPENAI_API_KEY="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"
NEWS_API_KEY = "4a3884100bd5453ca45eca7937d198ba"
ALPHA_VANTAGE_API_KEY = "F0YFPI6AVHE52EHL"
X-CMC_PRO_API_KEY = "440c12ff-74f9-4ff9-92a1-07345791e1cb"